# frozen_string_literal: true

source "https://rubygems.org" # rubocop:disable Style/StringLiterals

gem 'concurrent-ruby'
gem 'websocket-eventmachine-server'

gem 'rubocop', require: false
gem 'ruby-lsp'
