# frozen_string_literal: true

source "https://rubygems.org" # rubocop:disable Style/StringLiterals

gem 'concurrent-ruby'
gem 'em-websocket'

gem 'rubocop', require: false
gem 'ruby-lsp', require: false
